---
- name: set openshift_node_bootstrap to True when building AMI
  set_fact:
    openshift_node_bootstrap: True

# CONVERT TO COMMANDS
# az vm create --resource-group kwoodsontest --storage-account kwoodsonstorage --location eastus --name rhel7.4nomanaged --os-type linux --image https://kwoodsonstorage.blob.core.windows.net/images/rhel7.4_base.vhd --use-unmanaged-disk --ssh-key-value ~/Downloads/jimssh/id_rsa.pub --admin-username openshift  --storage-container images
- name: command version of create vm
  command: |
    az vm create \
      --resource-group {{ openshift_azure_resource_group_name }}
      --storage-account {{ openshift_azure_storage_account }}
      --storage-container {{ openshift_azure_storage_account_container }}
      --location {{ openshift_azure_resource_location }}
      --name {{ openshift_azure_vm_name }}
      --os-type linux
      --image {{ openshift_azure_vm_base_image }}
      --ssh-key-value "{{ openshift_azure_vm_ssh_public_keys[0].key_data }}"
      --admin-username {{ openshift_azure_vm_admin_username }}
      --use-unmanaged-disk
      --output json
  register: azurevm

# After meeting with MS and chatting with Harold Wong
# the azure_rm_virtualmachine module does not allow creating virtual machines with
# unmanaged disks.  Using unmanaged disks allows us to publish our image to the
#
#
#- name: Create virtual machine
#  azure_rm_virtualmachine:
#    resource_group: "{{ openshift_azure_resource_group_name }}"
#    name: "{{ openshift_azure_vm_name }}"
#    vm_size: "{{ openshift_azure_vm_size }}"
#    data_disks: "{{ openshift_azure_vm_data_disks }}"
#    storage_account_name: "{{ openshift_azure_storage_account_name }}"
#    storage_blob_name: "{{ openshift_azure_image_name }}" #rhel7.4_base_.vhd
#    storage_container_name: "{{ openshift_azure_storage_account_container }}"
#    admin_username: "{{ openshift_azure_vm_admin_username }}"
#    admin_password: "{{ openshift_azure_vm_admin_password | default(omit) }}"
#    ssh_password_enabled: "{{ openshift_azure_vm_ssh_pw_enabled }}"
#    network_interfaces: "{{ openshift_azure_virtual_network_name }}"
#    ssh_public_keys: "{{ openshift_azure_vm_ssh_public_keys if openshift_azure_vm_ssh_public_keys != [] else omit }}"
#    os_type: Linux
#    image: "{{ openshift_azure_vm_base_image }}"
#    #tags:
#      #nodes: 'node'
#  register: azurevm

- name: dump azurevm details
  debug:
    var: azurevm
    verbosity: 1

- meta: refresh_inventory

- name: debug inventory
  debug:
    msg: "{{ item }}"
  with_items: "{{ groups['azure'] }}"

- name: add azurevm to hosts
  add_host:
    groups: nodes,g_new_nodes_hosts
    name: "{{ azurevm.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"

#- name: Wait for SSH
#  wait_for_connection:
#  delegate_to: '{{ item }}'
#  with_items: '{{ groups["azure"] }}'
